# Generated by Django 6.0.7 on 2026-07-29 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_genre_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('review_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.review')),
            ],
        ),
    ]
