# Generated by Django 6.0.7 on 2026-07-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year_of_publishing',
        ),
    ]
