# Generated by Django 6.0.7 on 2026-07-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_annotation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_comment',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='review_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.review'),
        ),
    ]
